// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backTOT.Data;

#nullable disable

namespace backTOT.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250414112609_relationCart-User")]
    partial class relationCartUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backTOT.Entitys.Carts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Course_id")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Users_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Users_id")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("backTOT.Entitys.Courses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountDay")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Teacher_id")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Teacher_id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("backTOT.Entitys.Enrollments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Courses_id")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("End_date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Start_date")
                        .HasColumnType("date");

                    b.Property<int>("Student_id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("created_ad")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Courses_id");

                    b.HasIndex("Student_id");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("backTOT.Entitys.Lessons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Courses_id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Video_url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Courses_id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("backTOT.Entitys.Schedules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Class_time")
                        .HasColumnType("date");

                    b.Property<int>("Courses_id")
                        .HasColumnType("int");

                    b.Property<int>("Lessons_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Courses_id");

                    b.HasIndex("Lessons_id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("backTOT.Entitys.Scores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Courses_id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date_taken")
                        .HasColumnType("date");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Student_id")
                        .HasColumnType("int");

                    b.Property<string>("Test_name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Courses_id");

                    b.HasIndex("Student_id");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("backTOT.Entitys.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Des")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("USER");

                    b.Property<DateOnly>("created_ad")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backTOT.Entitys.Carts", b =>
                {
                    b.HasOne("backTOT.Entitys.Users", "user")
                        .WithOne("cart")
                        .HasForeignKey("backTOT.Entitys.Carts", "Users_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("backTOT.Entitys.Courses", b =>
                {
                    b.HasOne("backTOT.Entitys.Users", "user")
                        .WithMany("Courses")
                        .HasForeignKey("Teacher_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("backTOT.Entitys.Enrollments", b =>
                {
                    b.HasOne("backTOT.Entitys.Courses", "courses")
                        .WithMany("Enrollments")
                        .HasForeignKey("Courses_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backTOT.Entitys.Users", "user")
                        .WithMany("Enrollments")
                        .HasForeignKey("Student_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("courses");

                    b.Navigation("user");
                });

            modelBuilder.Entity("backTOT.Entitys.Lessons", b =>
                {
                    b.HasOne("backTOT.Entitys.Courses", "courses")
                        .WithMany("Lessons")
                        .HasForeignKey("Courses_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("courses");
                });

            modelBuilder.Entity("backTOT.Entitys.Schedules", b =>
                {
                    b.HasOne("backTOT.Entitys.Courses", "courses")
                        .WithMany("Schedules")
                        .HasForeignKey("Courses_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backTOT.Entitys.Lessons", "lessons")
                        .WithMany("Schedules")
                        .HasForeignKey("Lessons_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("courses");

                    b.Navigation("lessons");
                });

            modelBuilder.Entity("backTOT.Entitys.Scores", b =>
                {
                    b.HasOne("backTOT.Entitys.Courses", "courses")
                        .WithMany("Scores")
                        .HasForeignKey("Courses_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backTOT.Entitys.Users", "user")
                        .WithMany("Scores")
                        .HasForeignKey("Student_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("courses");

                    b.Navigation("user");
                });

            modelBuilder.Entity("backTOT.Entitys.Courses", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Lessons");

                    b.Navigation("Schedules");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("backTOT.Entitys.Lessons", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("backTOT.Entitys.Users", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Enrollments");

                    b.Navigation("Scores");

                    b.Navigation("cart")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
